# Generated by Django 3.1.1 on 2020-10-21 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=40, verbose_name='Nama Kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Judul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50, verbose_name='Judul')),
                ('nama', models.CharField(default='default', max_length=100, verbose_name='Nama File')),
                ('jumlah', models.IntegerField(null=True, verbose_name='Jumlah Halaman')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.kategori', verbose_name='Kategori')),
            ],
        ),
    ]
